name: class_example_app
description: Class example app
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
